#本地开发环境
server:
  port: 11000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: ops-dev
  datasource:
    url: jdbc:mysql://192.168.0.4:3306/ops?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123123
    username: root
  redis:
    host: 192.168.0.5
    password: 123123
    port: 6379
  rabbitmq:
    host: 192.168.0.6
    port: 5672
    username: root
    password: 123123
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual