#本地开发环境
server:
  port: 11000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: ops-dev
  datasource:
    url: jdbc:mysql://sh-cdb-0e99ru5c.sql.tencentcdb.com:62580/ops?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    password: TZH1234567890
    username: root
  redis:
    host: www.chuyinkeji.cn
    password: csb18857818257..
    port: 6379
  rabbitmq:
    host: www.chuyinkeji.cn
    port: 5672
    username: root
    password: tzh1234567890
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual